# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Validate Composer"
        run: "composer validate"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Downgrade PHPUnit"
        if: matrix.php-version == '7.2' || matrix.php-version == '7.3'
        run: "composer require --dev phpunit/phpunit:^7.5.20 --update-with-dependencies"

      - name: "Lint"
        run: "composer lint"

  coding-standards:
    name: "Coding Standard"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "latest"

      - name: "Validate Composer"
        run: "composer validate"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Lint"
        run: "composer lint"

      - name: "Coding Standard"
        run: "composer cs"

  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.3"
          - "8.4"
        dependencies:
          - "lowest"
          - "highest"
        coverage:
          - false
        include:
          - php: "8.2"
            coverage: true
            dependencies: "lowest"
          - php: "8.2"
            coverage: true
            dependencies: "highest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
          php-version: "${{ matrix.php-version }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "Downgrade PHPUnit"
        if: matrix.php-version == '7.2' || matrix.php-version == '7.3'
        run: "composer require --dev phpunit/phpunit:^7.5.20 --update-with-dependencies"

      - name: "Tests"
        run: "composer test"
        if: ${{ ! matrix.coverage }}

      - name: "Tests with coverage"
        run: "composer test -- --coverage-clover coverage.xml"
        if: ${{ matrix.coverage }}

      - name: "Upload code coverage report"
        uses: "codecov/codecov-action@v4.3.1"
        with:
          file: "coverage.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.coverage }}

  static-analysis:
    name: "PHPStan"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        dependencies:
          - "lowest"
          - "highest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          extensions: mbstring
          tools: composer:v2

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "Downgrade PHPUnit"
        if: matrix.php-version == '7.2' || matrix.php-version == '7.3'
        run: "composer require --dev phpunit/phpunit:^7.5.20 --update-with-dependencies"

      - name: "PHPStan"
        run: "composer phpstan"
